server:
  port: 8070

spring:
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 16
    port: 6379

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html
    encoding: UTF-8